import { toast } from 'sonner'
// Generated by vite-plugin-pwa at build time; aliased to registerSW.mock.ts
// under Vitest (see vite.config.ts) so tests never need the real plugin.
import { registerSW } from 'virtual:pwa-register'

/**
 * PWA update prompt (T6b): `registerType: 'prompt'` (not 'autoUpdate') —
 * an operator may have an add-entry sheet open with unsaved free-text mid-log
 * (uiStore's draft state is in-memory only, not persisted until "Guardar").
 * autoUpdate activates and reloads as soon as a new service worker is found,
 * which could silently drop that draft; a small toast lets the operator pick
 * a safe moment instead.
 */
export function setupPwaUpdatePrompt(): void {
  const updateSW = registerSW({
    onNeedRefresh() {
      toast('Nueva versión disponible', {
        duration: Infinity,
        action: {
          label: 'Actualizar',
          onClick: () => void updateSW(true),
        },
      })
    },
  })
}
